### ISSUE TITLE
[Feature Request] V4L support

### ISSUE THREAD

**Issue by edisionnano** [Soundux/rohrkabel#1]
It would be nice to be able to capture V4L devices like WebCams and capture cards. The way this works on Pipewire seems similar to how audio works. One example [here](https://docs.pipewire.org/local-v4l2_8c-example.html). I'd like to be able to list v4l devices (name and uuid) and be able to capture video from a v4l device specified by uuid (and perhaps select framerate and resolution mode if that is supported)

**Comment by Curve** [comment]
I added the possibility to bind devices easily, I don't plan to implement video-capture.

I'll mark this as closed, if you still have any suggestions or wishes feel free to reopen
