### ISSUE TITLE
Question: How to delete a link?

### ISSUE THREAD

**Issue by maltejur** [Soundux/rohrkabel#2]
Hi, thanks a lot for your library!

I am not that familiar with C++ and Pipewire so sorry if the answer is trivial. But after looking at the [link-app-to-mic](https://github.com/Soundux/rohrkabel/blob/master/examples/link-app-to-mic/main.cpp) example, I cant figure out how to delete a link again without deleting the whole microphone (I am searching for something like [this](https://github.com/Soundux/Soundux/blob/0849c68fb2362602c4127cb43b5b1ef2816e4f12/src/helper/audio/linux/pipewire/pipewire.cpp#L399)). Is this something still missing in the library or am I just doing something wrong?

**Comment by Curve** [comment]
All objects follow the RAII paradigm, that means if they go out of scope the object they hold will be deleted.

So: Make the object that holds the link go out of scope and it will be deleted (you could for example wrap it in a smart pointer and then reset that)

**Comment by Curve** [comment]
Hope that clarifies things, if you need any help let me know, I could also post an example in case that helps ^^

**Comment by maltejur** [comment]
> Hope that clarifies things

Yup, definitely. Thanks a lot for your answer!
