### ISSUE TITLE
Get rid of `#include <tl/expected.hpp>` and use `std::expected`

### ISSUE THREAD

**Issue by KOLANICH** [Soundux/rohrkabel#4]
Maybe optionally, using `__has_include` built-in preprocessor macro.

**Comment by Curve** [comment]
We don't use C++23 and std::expected isn't implemented in any major stable compiler release afaik (regarding clang, gcc)

**Comment by Curve** [comment]
Also, the next update will only bump the minimum C++ version to 20 and to 23.
